### ISSUE TITLE
Uptime not working

### ISSUE THREAD

**Issue by mweinelt** [czerwonk/bird_exporter#1]
Uptime parsing doesn't seem to work very well. I'm getting all zeroes for `_uptime` values.

You seem to call `birdc show protocols all`, but I can only find a timestamp in there, no timestamp or anything usable.

```
upstream    BGP      t_bgp    up     2017-02-20  Established   
lg_export   BGP      t_bgp    up     2017-04-05  Established   
```

Using bird 1.6.3.

**Comment by mweinelt** [comment]
Setting `timeformat protocol "%s";` reverts back to unix timestamps and fixes the parsing. Should probably be part of the README.

**Comment by czerwonk** [comment]
Thank you. The time format requirement is now part of README.
