### ISSUE TITLE
Precompiled binary ?

### ISSUE THREAD

**Issue by kormotodor** [czerwonk/bird_exporter#23]
Can you attach to release the precompiled binary?
Like that: "https://github.com/prometheus/node_exporter/releases/tag/v0.16.0"
Maybe just ".linux-amd64.tar.gz" for the firts time. 
It will be very nice)

**Comment by czerwonk** [comment]
I added cross compiled binaries for release 1.2.2 and will do so in future releases. Thanks for the request.

**Comment by kormotodor** [comment]
And what about release [1.2.3](https://github.com/czerwonk/bird_exporter/tree/1.2.3)?
