### ISSUE TITLE
Could you add tagged builds to docker hub?

### ISSUE THREAD

**Issue by captncraig** [czerwonk/bird_exporter#26]
I see that the docker image at https://hub.docker.com/r/czerwonk/bird_exporter is using automated builds on docker hub, which is great. 

For tracking versions of this project in our kubernetes cluster, it is nice to have more specific docker tags to reference. An easy way to get this is to just have docker hub build all tags, and then new github releases will get built to the appropriate tags automatically.

The config is rather easy to set up. Here's an example from a repo I have that does similar things:

![image](https://user-images.githubusercontent.com/192540/53177419-037b9580-35be-11e9-8bea-f39cfd2a07a8.png)

I think if you just set it up to build tags with the regex `/^v[0-9.]+$/`, it would just start working as new releases are pushed. That would be a really nice convenience going forward.

Thanks!

**Comment by czerwonk** [comment]
Release 1.2.3 introduces auto building for tagged docker releases.
