### ISSUE TITLE
Precompiled binary ? #2

### ISSUE THREAD

**Issue by kormotodor** [czerwonk/bird_exporter#28]
https://github.com/czerwonk/bird_exporter/issues/23

**Comment by bswinnerton** [comment]
I too would find this valuable for the latest release. Perhaps [GitHub Actions](https://github.com/features/actions) could do this automatically for us in the future?

**Comment by czerwonk** [comment]
Binaries will be added from 1.2.4 for each new release. I will test and consider using guthub actions for future release publishing.

**Comment by czerwonk** [comment]
1.2.4 binaries are now available
