### ISSUE TITLE
metrics 

### ISSUE THREAD

**Issue by armando-migliaccio** [czerwonk/bird_exporter#30]
Hi,

I have an issue to report, but first of all, I want to express my gratitude for the project!

The issue I am facing is this:

if the exporter is unable to connect to bird's socket (say because bird is down), it looks like the exporter's metric URL still returns HTTP 200, with an empty payload (Content-Length: 0); conversely, when the socket is accessible all is well and Content-Length is > 0.

This behavior of the exporter makes it harder to spot, from the standpoint of Prometheus, that the underlying sessions for a given instance (for instance bird_protocol_up) have gone down. I wonder if it would be more appropriate for the exporter to return an HTTP error code (like 503 or a generic 500), when the socket is unavailable or alternatively export a bird_status_up metric.

What is the suggestion on how to handle cases where the underlying bird process is unavailable?

Thanks!
Armando

**Comment by armando-migliaccio** [comment]
Steps to repro:

1) start the exporter and bird
2) call `curl -I http://<your-url>/metrics`
3) curl returns something like

```
HTTP/1.1 200 OK
Content-Length: 14272
Content-Type: text/plain; version=0.0.4
Date: Tue, 06 Aug 2019 20:03:47 GMT
```

4) stop bird
5) observe the following error in the exporter log: 

```
dial unix /var/run/bird.ctl: connect: connection refused  source="metric_collector.go:78"
```

6) Poke the metrics URL with curl to see the following:

```
HTTP/1.1 200 OK
Content-Length: 0
Content-Type: text/plain; version=0.0.4
Date: Tue, 06 Aug 2019 20:03:31 GMT
```

**Comment by armando-migliaccio** [comment]
@czerwonk thanks for ack-ing the issue! Any help I can provide, I'd love to help!

**Comment by ashepelev** [comment]
I have the same behavior
I have bird socket located in the other path. So I specify the path `-bird.socket /var/run/bird/bird.ctl` but still get the same problem.
curl returns 200 OK, exporter returns `level=error msg="dial unix /var/run/bird.ctl: connect: no such file or directory" source="metric_collector.go:78`

**Comment by ashepelev** [comment]
> I have the same behavior
> I have bird socket located in the other path. So I specify the path `-bird.socket /var/run/bird/bird.ctl` but still get the same problem.
> curl returns 200 OK, exporter returns `level=error msg="dial unix /var/run/bird.ctl: connect: no such file or directory" source="metric_collector.go:78`

sorry, wrong arguments syntax. I've missed `=` between arg and value

**Comment by tzockt** [comment]
Hi,
I habe the same Problem.  I have bird socket located in the other path. So I specify the path ``-bird.socket /var/run/bird/bird6.ctl`` but still get the same problem.
Version: 1.2.5
Exporter log: ``ERRO[0005] dial unix /var/run/bird.ctl: connect: no such file or directory  source="metric_collector.go:84"``

**Comment by czerwonk** [comment]
Hi,

i will have a look into this issue.

**Comment by czerwonk** [comment]
@tzockt if you want to specify an bird6 socket path:
``./bird_exporter -bird.socket6=/path/to/bird6-socket``
if you want to use it for bird6 only, you have to disable the scraping of bird4:
``./bird_exporter -bird.socket6=/path/to/bird6-socket --bird.ipv4=false``

**Comment by tzockt** [comment]
@czerwonk 
thx it works :)

**Comment by ecbaldwin** [comment]
I believe this issue may have been closed in err. It appears the resolution just before it got closed addressed @tzockt 's misconfiguration which was not related to the original bug. Unless I missed something.
