### ISSUE TITLE
Report whether OSPF session is running (or alone)

### ISSUE THREAD

**Issue by mweinelt** [czerwonk/bird_exporter#4]
An interesting metric would be to see whether the OSPF session is running [1] (or alone[0]), to spot potential misconfigurations.

- `ospf_running`
- `ospfv3_running`

**Comment by czerwonk** [comment]
Indeed, this would be an interesting metric. I will add this feature in the next days.

**Comment by czerwonk** [comment]
Managed to implement it today [see](https://github.com/czerwonk/bird_exporter/commit/c5d012cee01877c0169065430d9be3e5e37148e3)

Also there is now a metric for filtered routes

**Comment by mweinelt** [comment]
Yep, looks good, thanks.
