### ISSUE TITLE
bird2 compatibility issues

### ISSUE THREAD

**Issue by callMe-Root** [czerwonk/bird_exporter#52]
Hi, recently I've moved to bird2 and got a couple problems with it. 

- Installing with apt was failing due to dependencies since bird2 is not accepted instead of bird. I had to install it manually.
- I am trying to modify ARGS but not sure if doing it correctly? I am getting a blank page. From the syslog only thing I can see is /run/bird/bird6.ctl is not running error. I aware of it is not running and couldn't disable -bird.ipv6 option. What is the exact syntax? I've tried commenting out, -bird.ipv6=false, -bird.ipv6 false, none of them seems to work.  

Thanks in advance.

**Comment by valcryst** [comment]
Are you sure, youre using the bird2 flag?

```
  -bird.v2
        Bird major version >= 2.0 (multi channel protocols)
```

We use Bird2 with this exporter and we only set `-bird.socket` for ipv4 and ipv6 to work.

Full line
```
bird_exporter -bird.v2 -format.new=true -format.description-labels=true -bird.socket=/var/run/bird/bird.ctl -web.listen-address=127.0.0.1:9324 -proto.direct=false -proto.kernel=false -proto.static=false
```

**Comment by callMe-Root** [comment]
Hi, it works when disabled ipv6 or enabled birdv2. Looks like my typo. But the other problem still bothers me. I am downloading package and installing with "dpkg -i --ignore-depends=bird"
