### ISSUE TITLE
cannot load github.com/prometheus/common/log

### ISSUE THREAD

**Issue by aleksandrnikolaev** [czerwonk/bird_exporter#54]
I'm trying to install an exporter: go get -u github.com/czerwonk/bird_exporter
I get an error: 

go get -u github.com/czerwonk/bird_exporter
    go: finding golang.org/x/sys latest
    go: finding github.com/czerwonk/bird_socket latest
    build github.com/czerwonk/bird_exporter: cannot load github.com/prometheus/common/log: module 
    github.com/prometheus/common@latest found (v0.32.1), but does not contain package github.com/prometheus/common/log

How can I fix this bug?

**Comment by czerwonk** [comment]
Hi. I will have a look at it and provide a fix as soon as possible

**Comment by czerwonk** [comment]
Commit https://github.com/czerwonk/bird_exporter/commit/4b8417493df663f6d8a7b6c07c63c3dbeaafb00a fixes this issue:

# go get github.com/czerwonk/bird_exporter
go: downloading github.com/czerwonk/bird_exporter v0.0.0-20220113083838-be8305dd4b75
go: downloading github.com/prometheus/client_golang v1.11.0
go: downloading github.com/sirupsen/logrus v1.8.1
go: downloading github.com/czerwonk/bird_socket v0.0.0-20190111125930-6c39d61f8853
go: downloading github.com/prometheus/common v0.26.0
go: downloading golang.org/x/sys v0.0.0-20210603081109-ebe580a85c40
go: downloading gopkg.in/alecthomas/kingpin.v2 v2.2.6
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/golang/protobuf v1.4.3
go: downloading github.com/prometheus/procfs v0.6.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/alecthomas/template v0.0.0-20190718012654-fb15b899a751
go: downloading github.com/alecthomas/units v0.0.0-20190924025748-f65c72e2690d
go: downloading google.golang.org/protobuf v1.26.0-rc.1
go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.

**Comment by aleksandrnikolaev** [comment]
go get github.com/czerwonk/bird_exporter
package github.com/prometheus/common/log: cannot find package "github.com/prometheus/common/log" in any of:
	/usr/lib/go-1.13/src/github.com/prometheus/common/log (from $GOROOT)
	/root/go/src/github.com/prometheus/common/log (from $GOPATH)

**Comment by aleksandrnikolaev** [comment]
> Commit [4b84174](https://github.com/czerwonk/bird_exporter/commit/4b8417493df663f6d8a7b6c07c63c3dbeaafb00a) fixes this issue:
> 
> # go get github.com/czerwonk/bird_exporter
> go: downloading github.com/czerwonk/bird_exporter v0.0.0-20220113083838-be8305dd4b75 go: downloading github.com/prometheus/client_golang v1.11.0 go: downloading github.com/sirupsen/logrus v1.8.1 go: downloading github.com/czerwonk/bird_socket v0.0.0-20190111125930-6c39d61f8853 go: downloading github.com/prometheus/common v0.26.0 go: downloading golang.org/x/sys v0.0.0-20210603081109-ebe580a85c40 go: downloading gopkg.in/alecthomas/kingpin.v2 v2.2.6 go: downloading github.com/prometheus/client_model v0.2.0 go: downloading github.com/beorn7/perks v1.0.1 go: downloading github.com/cespare/xxhash/v2 v2.1.1 go: downloading github.com/golang/protobuf v1.4.3 go: downloading github.com/prometheus/procfs v0.6.0 go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1 go: downloading github.com/alecthomas/template v0.0.0-20190718012654-fb15b899a751 go: downloading github.com/alecthomas/units v0.0.0-20190924025748-f65c72e2690d go: downloading google.golang.org/protobuf v1.26.0-rc.1 go get: installing executables with 'go get' in module mode is deprecated. Use 'go install pkg@version' instead. For more information, see https://golang.org/doc/go-get-install-deprecation or run 'go help get' or 'go help install'.

go get github.com/czerwonk/bird_exporter
package github.com/prometheus/common/log: cannot find package "github.com/prometheus/common/log" in any of:
	/usr/lib/go-1.13/src/github.com/prometheus/common/log (from $GOROOT)
	/root/go/src/github.com/prometheus/common/log (from $GOPATH)

**Comment by aleksandrnikolaev** [comment]
I fixed this problem in a strange way by installing golang sources several times.
