### ISSUE TITLE
dial unix /var/run/bird.ctl

### ISSUE THREAD

**Issue by aleksandrnikolaev** [czerwonk/bird_exporter#55]
ERRO[0008] dial unix /var/run/bird.ctl: connect: no such file or directory

but i have bird.ctl in "/run/bird/bird.ctl"

How i can run exporter  with /run/bird/bird.ctl path?

**Comment by aleksandrnikolaev** [comment]
i fix this ./bird_exporter -bird.socket /var/run/bird.ctl
but: ERRO[0010] dial unix /run/bird6.ctl: connect: no such file or directory

How i can  use exporter without "-bird.socket6 /run/bird6.ctl" ??

**Comment by czerwonk** [comment]
Which version of bird do you use?

**Comment by aleksandrnikolaev** [comment]
> Which version of bird do you use?

BIRD version 1.6.8

**Comment by czerwonk** [comment]
Please set the option ``-bird.ipv6`` to ``false``. Then this should work.

**Comment by aleksandrnikolaev** [comment]
> Please set the option `-bird.ipv6` to `false`. Then this should work.

Thank you very much! that's how it works!  And it also works like this:
-bird.socket /var/run/bird.ctl -bird.socket6=/var/run/bird.ctl
