### ISSUE TITLE
bfd sessions

### ISSUE THREAD

**Issue by aleksandrnikolaev** [czerwonk/bird_exporter#56]
how can I see the metrics of bfd sessions? Interested in at least the status (up/down).

They are displayed by the command: birdc show bfd sesssions

**Comment by czerwonk** [comment]
This is not implemented yet. Can you provide (anonymized) output for ``birdc show bfd sessions``?

**Comment by aleksandrnikolaev** [comment]
> This is not implemented yet. Can you provide (anonymized) output for `birdc show bfd sessions`?

 birdc show bfd session
BIRD 1.6.8 ready.
bfd20: ##this is short name for bgp session in bird.conf ( protocol bfd bfd20 { ............... )
IP address                                   Interface  State             Since        Interval  Timeout
ip_bfd_with_other_server              ---            Up         2022-01-12    0.400    1.200
ip_bfd_with_other_server              ---            Up         2022-01-14    0.400    2.000
ip_gw1                                         ens192     Up         2022-01-12    0.400    2.000
ip_bfd_with_other_server              ens192     Up         2022-01-12    0.400    2.000
ip_bfd_with_other_server              ---            Up         2022-01-12    0.400    2.000
ip_bfd_with_other_server             ens192      Up         2022-01-12    0.400    2.000
ip_bfd_with_other_server             ens192      Up         2022-01-12    0.400    2.000
ip_gw                                          ens192      Up         2022-01-12    0.400    2.000
ip_bfd_with_other_server              ---            Up         2022-01-12    0.400    1.200

it is very important to have: state , since, interval and timeout status.

but the most important thing is to see the session status: "Up/Down/Init"

**Comment by nwton** [comment]
This problem affects me too. How difficult is it to implement this feature in code?

**Comment by czerwonk** [comment]
Feature is included in Version 1.4, wich was released a few moments ago.

**Comment by unixsurfer** [comment]
I have a [PR](https://github.com/czerwonk/bird_exporter/pull/97) related to this.

**Comment by czerwonk** [comment]
[PR](#97) was merged and new tag was created
