### ISSUE TITLE
Zabbix Integration

### ISSUE THREAD

**Issue by interduo** [czerwonk/bird_exporter#76]
I see the good code here ... You have done 95% code also for integration with zabbix.

Is it possible to print all the metrics from BGP on screen using some compact format like CSV?

I would like to use zabbix_sender (https://github.com/zarplata/zabbix-sender-php) then to send all the values to zabbix.

**Comment by paketb0te** [comment]
If you insist on using Zabbix, apparently it has support for reading data in the prometheus format: [Prometheus checks](https://www.zabbix.com/documentation/current/en/manual/config/items/itemtypes/prometheus)

But honestly, do yourself a favor and ditch Zabbix ;)

**Comment by interduo** [comment]
Thanks for the answer.

> But honestly, do yourself a favor and ditch Zabbix ;)

Yes - it has got some underdeveloped features but ... it's not that bad in broader view. It's better than nagios or cacti.

**Comment by paketb0te** [comment]
> It's better than nagios or cacti.
I can't really speak to that, as I've used neither nagios nor cacti.
But I *do* have a direct comparison between Zabbix and Prometheus, and that comparison is *very* unfavorable for Zabbix.

**Comment by interduo** [comment]
sorry for making an offtopic but its also important topic for me: 
What is advantage of Prometheus comparing to Zabbix?

**Comment by paketb0te** [comment]
Reason #1 for me is the query language.

I find it *much* easier to define alerts etc. in PromQL than with zabbix checks.

Other reasons, in no particular order:
- better performance
- super easy to expose metrics (if you develop an application)
- there are exporters (small tools that transform metrics into Prometheus-readable format) for *many* things, and it is quite simple to write one if it does not exist for your use case - I find it much more elegant than having to run some script every poll cycle with zabbix.
- the accompanying [Alertmanager](https://prometheus.io/docs/alerting/latest/alertmanager/) is a great tool for Alert handling

I acknowledge that I am probably a bit biased, but just recently I tried to build a check in Zabbix that compares the current value of a metric with a previous value - it worked in the end, but the syntax was just so terrible, it was quite a frustrating experience.

**Comment by interduo** [comment]
Yes - query language is not as pleasant as it could be but it's not totally awful ;-)
I don't have a performance issues - the default install of postgresql instance needs some db tunning.
That is nice I didn't try this in zabbix - some day I will write an integration with our CRM.
Yeah exporters looks very useful.
I use Telegram and Slack transport instead of other application for me it's better.

One more time - thanks for Your point of view! Some day I will try Prometheus if zabbix will be botleneck.
